spring:
  #\u914D\u7F6E\u6570\u636E\u6E90
  datasource:
    #\u57FA\u672C\u6570\u636E\u53C2\u6570\u914D\u7F6E
    username: root
    password: bsy8023.00
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    
mybatis-plus:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
  global-config:
    db-config:
      #逻辑删除
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
